### ISSUE TITLE
"Could not Connect to Worx Server" since today

### ISSUE THREAD

**Issue by tobihoby** [normen/homebridge-landroid#18] opened 2020-04-10 13:30 UTC
[Homebridge] [4/10/2020, 15:23:07] [Landroid] Could not Connect to Worx Server: RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
[Homebridge] [4/10/2020, 15:23:07] [Landroid] RequestError: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
    at new RequestError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'RequestError',
  message: 'Error: getaddrinfo EAI_AGAIN api.worxlandroid.com',
  cause: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    errno: 'EAI_AGAIN',
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'api.worxlandroid.com'
  },
  error: Error: getaddrinfo EAI_AGAIN api.worxlandroid.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    errno: 'EAI_AGAIN',
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'api.worxlandroid.com'
  },
  options: {
    method: 'POST',
    uri: 'https://api.worxlandroid.com/api/v2/oauth/token',
    headers: { 'Content-Type': 'application/json' },
    body: {
      username: '**********@gmail.com',
      password: '**********',
      grant_type: 'password',
      client_id: 1,
      type: 'app',
      client_secret: '*******************************************',
      scope: '*'
    },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by normen** [comment] 2020-04-10 15:52
Using the latest version of the plugin I can connect to the worx cloud so its unlikely that the worx API or server changed again. Since it worked before for you I assume thats an issue in your network, maybe try if the app works.

The error basically just says that it couldn't connect to the worx server. Closing this as its expected behavior.

**Closed as completed by normen** 2020-04-10 15:52 UTC
